modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
[[mods]]
modId="telegrambridge"
version="0.0.1"
displayName="TelegramBridge"
authors="Nick Robson"
description='''
Relays messages between Minecraft and Telegram
'''
[[dependencies.telegrambridge]] #optional
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.telegrambridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"